# Generated by Django 4.0.4 on 2022-05-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesListApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='MoviesListApp.project'),
            preserve_default=False,
        ),
    ]
