# Generated by Django 4.0.4 on 2022-05-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='project name', max_length=100)),
                ('creation_time', models.DateField(help_text='date the project ')),
                ('completion_time', models.DateField(help_text='completion time')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title', max_length=100)),
                ('description', models.TextField(help_text='description ')),
                ('date', models.DateField(help_text='Description.')),
                ('time_estimate', models.IntegerField(help_text='time')),
                ('completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMApp.project')),
            ],
        ),
    ]
