# Generated by Django 4.0.4 on 2022-05-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of list', max_length=50)),
                ('website', models.URLField(help_text='URL of list', max_length=100)),
                ('email', models.EmailField(help_text='Email for the list', max_length=254)),
            ],
        ),
    ]
